#!/bin/bash

sudo ifconfig vmnet8 down
sudo ifconfig vmnet1 down
sudo ifconfig vmnet2 down
figlet -kc "VMWARE network down"
echo "Active interfaces are :"
echo "-----------------------"
ip addr | grep UP | cut -f2 -d":" 
